
# Rocks:
Rock.create(name:"Gneiss", image_url:"https://geology.com/rocks/pictures/gneiss.jpg", description:"Gneiss is a foliated metamorphic rock identified by its bands and lenses of varying composition, while other bands contain granular minerals with an interlocking texture. Other bands contain platy or elongate minerals with evidence of preferred orientation. It is this banded appearance and texture - rather than composition - that define a gneiss.", price:47, category:"Metamorphic", color:"Grey", rating:5, quantity:200)
Rock.create(name:"Caliche", image_url:"https://geology.com/rocks/pictures/calcrete.jpg", description:"Caliche is a shallow layer of soil or sediment in which the particles have been cemented together by the precipitation of mineral matter in their interstitial spaces. The cement is usually calcium carbonate; however, cements of magnesium carbonate, gypsum, silica, iron oxide, and a combination of these materials are known. Caliche is a common feature of arid or semiarid areas throughout the world. In the United States, caliche is a familiar deposit in many parts of the Southwest, especially in Arizona, California, Nevada, New Mexico, and Texas. There, caliche is associated with problems such as poor soil drainage, difficult soil conditions for plant growth, and excavation problems at construction sites. In some locations there are multiple ancient caliche layers in the subsurface. The name 'caliche' originates from a Spanish word for porous materials that have been cemented by calcium carbonate. The name is used to refer to a piece of the material or the layer from which it was broken, or the cement itself that binds the materials together. Caliche is known by many other names, the more common of which are calcrete, hardpan, duricrust, and calcic soil.", price:12, category:"Sedimentary", color:"white", rating:5, quantity:12)
Rock.create(name:"skarn", image_url:"https://geology.com/rocks/pictures/garnet-skarn.jpg", description:"Skarn is a metamorphic rock that has been chemically and mineralogically altered by metasomatism. Metasomatism is the alteration of rocks by hot, chemically-active fluids that flow or diffuse through the rocks and cause recrystallization and compositional change. Skarn commonly forms around the edges of a magma body that intrudes a nearby rock mass. Rocks formed or altered by the interaction of magma, country rock, reactive fluids and heat are known as skarn. Other environments of metasomatic activity are also known to produce skarn.", price:65, category:"Metamorphic", color:"Red", rating:5, quantity:38)
Rock.create(name:"Geode", image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Terra_Mineralia...2H1A6825%D0%9E%D0%92.jpg/1024px-Terra_Mineralia...2H1A6825%D0%9E%D0%92.jpg", description:'Geodes (derived from the Greek word "γεώδης" meaning "Earth like") are geological secondary formation within sedimentary and volcanic rocks. Geodes are hollow, vaguely circular rocks, in which masses of mineral matter (which may include crystals) are secluded. The crystals are formed by the filling of vesicles in volcanic and sub-volcanic rocks by minerals deposited from hydrothermal fluids; or by the dissolution of syn-genetic concretions and partial filling by the same, or other minerals precipitated from water, groundwater or hydrothermal fluids. ', price:52, category:"Special", color:"Multi", rating:5, quantity:42)
Rock.create(name:"Septarian Nodule", image_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Septarian_Nodule.jpg/450px-Septarian_Nodule.jpg", description:'Septarian concretions or septarian nodules, are concretions containing angular cavities or cracks, called "septaria". The word comes from the Latin word septum; "partition", and refers to the cracks/separations in this kind of rock. Some websites incorrectly derive the term from the Latin word septem, meaning "seven". Cracks are highly variable in shape and volume, as well as the degree of shrinkage they indicate. Although it has commonly been assumed that concretions grew incrementally from the inside outwards, the fact that radially oriented cracks taper towards the margins of septarian concretions is taken as evidence that in these cases the periphery was stiffer while the inside was softer, presumably due to a gradient in the amount of cement precipitated. The process that created the septaria that characterize septarian concretions remains unclear. A number of mechanisms have been proposed, including the dehydration of clay-rich, gel-rich, or organic-rich cores; shrinkage of the concretion\'s center; expansion of gases produced by the decay of organic matter; or brittle fracturing or shrinkage of the concretion interior by either earthquakes or compaction. Septaria usually contain crystals, often calcite, that precipitated from circulating solutions. Siderite or pyrite coatings are also occasionally observed on the wall of the cavities present in the septaria, giving rise respectively to a panoply of bright reddish and golden colors.', price:75, category:"special", color:"brown", rating:3, quantity:48)
Rock.create(name:"Thunderegg", image_url:"https://i.pinimg.com/originals/52/52/cc/5252cc0b54e87b274f9c3efc995274ef.jpg", description:"Thundereggs are agate-filled nodules found in various parts of the Western United States. They range in size from 1/4 inch to as large as 5 feet in diameter. Generally, they are about the size of oranges. All are similar on the exterior, but no two are alike in pattern, design or color on the inside. The most colorful and beautiful of Thundereggs comes from a small area in Jefferson County in Central Oregon (Pony Butte). In other localities they do not show such brilliant color and gem quality. In spite of their superior quality, only one in an average of twenty cut make outstanding specimens. These show vivid scenes of land and sea fantasies, which besides the bright hues, reveal the appearance of depth and dimension of distance. Cut and polished Thundereggs are beautiful to behold. They are one of the marvels of nature and are sought after and highly prized the world over.", price:500, category:"Special", color:"Multi", rating:5, quantity:50)
Rock.create(name:"Damn Ass Rock", image_url:"https://i.ytimg.com/vi/Gpmei-6u2OQ/maxresdefault.jpg", description:"It was this damn ass rock!", price:1, category:"Dangerous", color:"brown", rating:1, quantity:1)
Rock.create(name:"Amethyst", image_url:"https://geology.com/gemstones/amethyst/amethyst-crystals.jpg", description:"Amethyst is the purple color variety of quartz. It is the most popular purple gem and one of the most popular gemstones of all time. Amethyst is used to produce faceted stones, cabochons, beads, tumbled stones, and many other items for jewelry and ornamental use. Amethyst has a Mohs hardness of 7 and does not break by cleavage. It is a gem that is durable enough for use in rings, earrings, pendants, bracelets and other types of jewelry. Enormous deposits of amethyst in South America and Africa provide enough material to keep amethyst’s price low enough that most people can easily afford it.", price:275, category:"Fancy", color:"Purple", rating:4, quantity:17)
Rock.create(name:"Regular", image_url:"https://res.cloudinary.com/dk-find-out/image/upload/q_80,w_1920,f_auto/Limestone-060-RD010-C-SH_by22j3.jpg", description:"Just a regular rock", price:1, category:"Boring", color:"Grey", rating:1, quantity:20000)
Rock.create(name:"Obsidian", image_url:"https://geology.com/rocks/pictures/obsidian-380.jpg", description:"Obsidian is an igneous rock that forms when molten rock material cools so rapidly that atoms are unable to arrange themselves into a crystalline structure. It is an amorphous material known as a 'mineraloid.' The result is a volcanic glass with a smooth uniform texture that breaks with a conchoidal fracture", price:17, category:"Igneous", color:"Black", rating:3, quantity:47)
Rock.create(name:"Orpiment", image_url:"https://i4w8j7y6.stackpathcdn.com/wp-content/uploads/2015/08/07Orpiment_thumb.jpg", description:"Found near hydrothermal vents, these rocks are made of arsenic and sulfur. Touching them is enough to release a neurotoxin", price:600, category:"Danger", color:"Red", rating:2, quantity:3)
Rock.create(name:"Torbernite", image_url:"https://cdn.irocks.com/storage/media/52992/conversions/MD-120981a-large.jpg", description:"Found in granite and made of uranium, these green crystals have been long admired by collectors. As well as being radioactive however, the rocks release deadly radon gas when heated.", price:350, category:"Danger", color:"Green", rating:1, quantity:1)
Rock.create(name:"Fluorite", image_url:"https://geology.com/minerals/photos/fluorite.jpg", description:'Fluorite is an important industrial mineral composed of calcium and fluorine (CaF2). It is used in a wide variety of chemical, metallurgical, and ceramic processes. Specimens with exceptional diaphaneity and color are cut into gems or used to make ornamental objects. Fluorite is deposited in veins by hydrothermal processes. In these rocks it often occurs as a gangue mineral associated with metallic ores. Fluorite is also found in the fractures and cavities of some limestones and dolomites. It is a very common rock-forming mineral found in many parts of the world. In the mining industry, fluorite is often called "fluorspar.', price:50, category:"Fancy", color:"Blue", rating:4, quantity:13)

#Users:



puts "Successful seed!"